import Head from "next/head";
import AddMovie from "../src/addMovie";
import { MovieProvider } from "../src/movieContext";
import MoviesList from "../src/movieList";
import Nav from "../src/nav";
import styles from "../styles/Home.module.css";

export default function Home({deleteMovie}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MovieProvider>
          <Nav />
          <AddMovie />
          <MoviesList setMovies={deleteMovie} />
        </MovieProvider>
      </main>
    </div>
  );
}
